jobs:
  rotate_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Rotate Image
      run: |
        # Your image rotation logic
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the stored token

    - name: Commit and Push Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
        git add .
        git commit -m "Updated challenge image"
        git push
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Make sure the token is available
